CREATE TABLE NHIEM_VU_DU_AN (
    MANVDA INT IDENTITY(1,1) PRIMARY KEY,
    MADA INT,
    MANV VARCHAR(20),
    TENNHIEMVU NVARCHAR(255),
    MOTA NVARCHAR(MAX),
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
    DOUUTIEN NVARCHAR(20),
    TRANGTHAI NVARCHAR(50),
    PHANTRAMHOANTHANH INT,
    GHICHUSAUHOANTHANH NVARCHAR(MAX),
    CREATEDAT DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_NHIEMVU_DUAN FOREIGN KEY (MADA) REFERENCES DU_AN(MADA) ON DELETE CASCADE,
    CONSTRAINT FK_NHIEMVU_PHANCONG FOREIGN KEY (MADA, MANV) REFERENCES PHANCONG_DU_AN(MaDA, MaNV) ON DELETE NO ACTION
);
GO

CREATE OR ALTER PROCEDURE sp_isEmployeeInProject
    @MADA INT,
    @MANV VARCHAR(20)
AS
BEGIN
    SELECT 1 FROM PHAN_CONG_DU_AN WHERE MADA = @MADA AND MANV = @MANV;
END;
GO

CREATE OR ALTER PROCEDURE sp_getProjectMemberRole
    @MADA INT,
    @MANV VARCHAR(20)
AS
BEGIN
    SELECT VaiTroDuAn FROM PHAN_CONG_DU_AN WHERE MADA = @MADA AND MANV = @MANV;
END;
GO

CREATE OR ALTER PROCEDURE sp_getProjectTasks
    @MADA INT
AS
BEGIN
    SELECT * FROM NHIEM_VU_DU_AN WHERE MADA = @MADA;
END;
GO

CREATE OR ALTER PROCEDURE sp_createProjectTask
    @MADA INT,
    @MANV VARCHAR(20),
    @TENNHIEMVU NVARCHAR(255),
    @MOTA NVARCHAR(MAX),
    @NGAYBATDAU DATE,
    @NGAYKETTHUC DATE,
    @DOUUTIEN NVARCHAR(20),
    @TRANGTHAI NVARCHAR(50),
    @PHANTRAMHOANTHANH INT,
    @GHICHUSAUHOANTHANH NVARCHAR(MAX)
AS
BEGIN
    INSERT INTO NHIEM_VU_DU_AN (MADA, MANV, TENNHIEMVU, MOTA, NGAYBATDAU, NGAYKETTHUC, DOUUTIEN, TRANGTHAI, PHANTRAMHOANTHANH, GHICHUSAUHOANTHANH)
    OUTPUT INSERTED.*
    VALUES (@MADA, @MANV, @TENNHIEMVU, @MOTA, @NGAYBATDAU, @NGAYKETTHUC, @DOUUTIEN, @TRANGTHAI, @PHANTRAMHOANTHANH, @GHICHUSAUHOANTHANH);
END;
GO

CREATE OR ALTER PROCEDURE sp_getTaskByIdInProject
    @MADA INT,
    @MANVDA INT
AS
BEGIN
    SELECT * FROM NHIEM_VU_DU_AN WHERE MADA = @MADA AND MANVDA = @MANVDA;
END;
GO

CREATE OR ALTER PROCEDURE sp_updateProjectTask
    @MADA INT,
    @MANVDA INT,
    @MANV VARCHAR(20),
    @MANV_PASSED BIT,
    @TENNHIEMVU NVARCHAR(255),
    @TENNHIEMVU_PASSED BIT,
    @MOTA NVARCHAR(MAX),
    @MOTA_PASSED BIT,
    @NGAYBATDAU DATE,
    @NGAYBATDAU_PASSED BIT,
    @NGAYKETTHUC DATE,
    @NGAYKETTHUC_PASSED BIT,
    @DOUUTIEN NVARCHAR(20),
    @DOUUTIEN_PASSED BIT,
    @TRANGTHAI NVARCHAR(50),
    @TRANGTHAI_PASSED BIT,
    @PHANTRAMHOANTHANH INT,
    @PHANTRAMHOANTHANH_PASSED BIT,
    @GHICHUSAUHOANTHANH NVARCHAR(MAX),
    @GHICHUSAUHOANTHANH_PASSED BIT
AS
BEGIN
    UPDATE NHIEM_VU_DU_AN
    SET
        MANV = CASE WHEN @MANV_PASSED = 1 THEN @MANV ELSE MANV END,
        TENNHIEMVU = CASE WHEN @TENNHIEMVU_PASSED = 1 THEN @TENNHIEMVU ELSE TENNHIEMVU END,
        MOTA = CASE WHEN @MOTA_PASSED = 1 THEN @MOTA ELSE MOTA END,
        NGAYBATDAU = CASE WHEN @NGAYBATDAU_PASSED = 1 THEN @NGAYBATDAU ELSE NGAYBATDAU END,
        NGAYKETTHUC = CASE WHEN @NGAYKETTHUC_PASSED = 1 THEN @NGAYKETTHUC ELSE NGAYKETTHUC END,
        DOUUTIEN = CASE WHEN @DOUUTIEN_PASSED = 1 THEN @DOUUTIEN ELSE DOUUTIEN END,
        TRANGTHAI = CASE WHEN @TRANGTHAI_PASSED = 1 THEN @TRANGTHAI ELSE TRANGTHAI END,
        PHANTRAMHOANTHANH = CASE WHEN @PHANTRAMHOANTHANH_PASSED = 1 THEN @PHANTRAMHOANTHANH ELSE PHANTRAMHOANTHANH END,
        GHICHUSAUHOANTHANH = CASE WHEN @GHICHUSAUHOANTHANH_PASSED = 1 THEN @GHICHUSAUHOANTHANH ELSE GHICHUSAUHOANTHANH END
    OUTPUT INSERTED.*
    WHERE MADA = @MADA AND MANVDA = @MANVDA;
END;
GO

CREATE OR ALTER PROCEDURE sp_getAllProjects
AS
BEGIN
    SELECT * FROM DU_AN;
END;
GO

CREATE OR ALTER PROCEDURE sp_getProjectById
    @MADA INT
AS
BEGIN
    SELECT * FROM DU_AN WHERE MADA = @MADA;
END;
GO

CREATE OR ALTER PROCEDURE sp_getProjectMembers
    @MADA INT
AS
BEGIN
    SELECT pc.*, nv.TENNV, nv.EMAIL 
    FROM PHAN_CONG_DU_AN pc
    LEFT JOIN NHAN_VIEN nv ON pc.MANV = nv.MANV
    WHERE pc.MADA = @MADA;
END;
GO

CREATE OR ALTER PROCEDURE sp_getEmployeeProjects
    @MANV VARCHAR(20)
AS
BEGIN
    SELECT da.* 
    FROM DU_AN da
    INNER JOIN PHAN_CONG_DU_AN pc ON da.MADA = pc.MADA
    WHERE pc.MANV = @MANV;
END;
GO

CREATE OR ALTER PROCEDURE sp_getProjectsWithMembersByEmployee
    @MANV VARCHAR(20)
AS
BEGIN
    SELECT da.* 
    FROM DU_AN da
    INNER JOIN PHAN_CONG_DU_AN pc ON da.MADA = pc.MADA
    WHERE pc.MANV = @MANV;
END;
GO

CREATE OR ALTER PROCEDURE sp_createProject
    @TENDA NVARCHAR(255),
    @MOTA NVARCHAR(MAX),
    @NGAYBATDAU DATE,
    @NGAYKETTHUC DATE,
    @TRANGTHAI NVARCHAR(50)
AS
BEGIN
    INSERT INTO DU_AN (TENDA, MOTA, NGAYBATDAU, NGAYKETTHUC, TRANGTHAI)
    OUTPUT INSERTED.*
    VALUES (@TENDA, @MOTA, @NGAYBATDAU, @NGAYKETTHUC, @TRANGTHAI);
END;
GO

CREATE OR ALTER PROCEDURE sp_updateProject
    @MADA INT,
    @TENDA NVARCHAR(255),
    @TENDA_PASSED BIT,
    @MOTA NVARCHAR(MAX),
    @MOTA_PASSED BIT,
    @NGAYBATDAU DATE,
    @NGAYBATDAU_PASSED BIT,
    @NGAYKETTHUC DATE,
    @NGAYKETTHUC_PASSED BIT,
    @TRANGTHAI NVARCHAR(50),
    @TRANGTHAI_PASSED BIT
AS
BEGIN
    UPDATE DU_AN
    SET 
        TENDA = CASE WHEN @TENDA_PASSED = 1 THEN @TENDA ELSE TENDA END,
        MOTA = CASE WHEN @MOTA_PASSED = 1 THEN @MOTA ELSE MOTA END,
        NGAYBATDAU = CASE WHEN @NGAYBATDAU_PASSED = 1 THEN @NGAYBATDAU ELSE NGAYBATDAU END,
        NGAYKETTHUC = CASE WHEN @NGAYKETTHUC_PASSED = 1 THEN @NGAYKETTHUC ELSE NGAYKETTHUC END,
        TRANGTHAI = CASE WHEN @TRANGTHAI_PASSED = 1 THEN @TRANGTHAI ELSE TRANGTHAI END
    WHERE MADA = @MADA;
END;
GO

CREATE OR ALTER PROCEDURE sp_deleteProjectTasks
    @MADA INT
AS
BEGIN
    DELETE FROM NHIEM_VU_DU_AN WHERE MADA = @MADA;
END;
GO

CREATE OR ALTER PROCEDURE sp_deleteProjectAssignments
    @MADA INT
AS
BEGIN
    DELETE FROM PHAN_CONG_DU_AN WHERE MADA = @MADA;
END;
GO

CREATE OR ALTER PROCEDURE sp_deleteProject
    @MADA INT
AS
BEGIN
    DELETE FROM DU_AN WHERE MADA = @MADA;
END;
GO

CREATE OR ALTER PROCEDURE sp_addProjectMember
    @MADA INT,
    @MANV VARCHAR(20),
    @VAITRODUAN NVARCHAR(100)
AS
BEGIN
    INSERT INTO PHAN_CONG_DU_AN (MADA, MANV, VAITRODUAN)
    VALUES (@MADA, @MANV, @VAITRODUAN);
END;
GO

CREATE OR ALTER PROCEDURE sp_removeProjectMember
    @MADA INT,
    @MANV VARCHAR(20)
AS
BEGIN
    DELETE FROM PHAN_CONG_DU_AN 
    WHERE MADA = @MADA AND MANV = @MANV;
    
    SELECT @@ROWCOUNT AS RemovedMemberCount;
END;
GO