version: '3.8'

services:
  erp-backend:
    container_name: danghoa-erp-backend
    image: ${DOCKER_USERNAME}/danghoa-erp-backend:latest
    restart: always
    network_mode: "host"
    environment:
      - NODE_ENV=production
      # Các biến môi trường khác (DB, JWT Secret, v.v.)
      # sẽ được lấy từ file .env nằm trên máy chủ (được khai báo ở dưới)
    env_file:
      - .env
