-- Create Tables
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHONG_CHAT]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[PHONG_CHAT](
        [MAPHONG] [int] IDENTITY(1,1) NOT NULL,
        [TENPHONG] [nvarchar](255) NULL,
        [LOAIPHONG] [tinyint] NOT NULL,
        [MATHAMCHIEU] [varchar](50) NULL,
        [NGAYTAO] [datetime] NULL DEFAULT (getdate()),
        CONSTRAINT [PK_PHONG_CHAT] PRIMARY KEY CLUSTERED ([MAPHONG] ASC)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[THANH_VIEN_PHONG_CHAT]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[THANH_VIEN_PHONG_CHAT](
        [MAPHONG] [int] NOT NULL,
        [MANV] [varchar](20) NOT NULL,
        [VAITRO] [nvarchar](50) NULL DEFAULT (N'Thành viên'),
        [NGAYTHAMGIA] [datetime] NULL DEFAULT (getdate()),
        CONSTRAINT [PK_THANH_VIEN_PHONG_CHAT] PRIMARY KEY CLUSTERED ([MAPHONG] ASC, [MANV] ASC)
    )
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIN_NHAN]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[TIN_NHAN](
        [MATN] [int] IDENTITY(1,1) NOT NULL,
        [MAPHONG] [int] NOT NULL,
        [MANV_GUI] [varchar](20) NOT NULL,
        [NOIDUNG] [nvarchar](max) NOT NULL,
        [FILEURL] [nvarchar](max) NULL,
        [FILETYPE] [varchar](50) NULL,
        [THOIGIANGUI] [datetime] NULL DEFAULT (getdate()),
        CONSTRAINT [PK_TIN_NHAN] PRIMARY KEY CLUSTERED ([MATN] ASC)
    )
END
GO

-- Stored Procedures

CREATE OR ALTER PROCEDURE sp_getMyRooms
    @MaNV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    
    SELECT 
        p.MAPHONG,
        p.TENPHONG,
        p.LOAIPHONG,
        p.MATHAMCHIEU,
        p.NGAYTAO,
        (SELECT COUNT(*) FROM THANH_VIEN_PHONG_CHAT tv2 WHERE tv2.MAPHONG = p.MAPHONG) AS SoThanhVien,
        (SELECT TOP 1 NOIDUNG FROM TIN_NHAN tn WHERE tn.MAPHONG = p.MAPHONG ORDER BY THOIGIANGUI DESC) AS TinNhanGanNhat
    FROM PHONG_CHAT p
    INNER JOIN THANH_VIEN_PHONG_CHAT tv ON p.MAPHONG = tv.MAPHONG
    WHERE tv.MANV = @MaNV
    ORDER BY (SELECT TOP 1 THOIGIANGUI FROM TIN_NHAN tn WHERE tn.MAPHONG = p.MAPHONG ORDER BY THOIGIANGUI DESC) DESC;
END
GO

CREATE OR ALTER PROCEDURE sp_isRoomMember
    @MaPhong INT,
    @MaNV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MAPHONG, MANV FROM THANH_VIEN_PHONG_CHAT
    WHERE MAPHONG = @MaPhong AND MANV = @MaNV;
END
GO

CREATE OR ALTER PROCEDURE sp_getRoomById
    @MaPhong INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MAPHONG, TENPHONG, LOAIPHONG, MATHAMCHIEU, NGAYTAO 
    FROM PHONG_CHAT 
    WHERE MAPHONG = @MaPhong;
END
GO

CREATE OR ALTER PROCEDURE sp_getRoomMessages
    @MaPhong INT,
    @Limit INT = 50
AS
BEGIN
    SET NOCOUNT ON;
    -- Note: Assuming table NHANVIEN has columns MANV and TENNV
    SELECT TOP (@Limit)
        tn.MATN,
        tn.MAPHONG,
        tn.MANV_GUI,
        nv.TENNV AS TenNguoiGui,
        tn.NOIDUNG,
        tn.THOIGIANGUI
    FROM TIN_NHAN tn
    LEFT JOIN NHANVIEN nv ON tn.MANV_GUI = nv.MANV
    WHERE tn.MAPHONG = @MaPhong
    ORDER BY tn.THOIGIANGUI DESC;
END
GO

CREATE OR ALTER PROCEDURE sp_getLatestMessageByRoom
    @MAPHONG INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP 1 MATN, MAPHONG, MANV_GUI, NOIDUNG, THOIGIANGUI
    FROM TIN_NHAN
    WHERE MAPHONG = @MAPHONG
    ORDER BY THOIGIANGUI DESC;
END
GO

CREATE OR ALTER PROCEDURE sp_searchMessagesByKeyword
    @MAPHONG INT,
    @TUKHOA NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MATN, MAPHONG, MANV_GUI, NOIDUNG, THOIGIANGUI
    FROM TIN_NHAN
    WHERE MAPHONG = @MAPHONG AND NOIDUNG LIKE N'%' + @TUKHOA + N'%'
    ORDER BY THOIGIANGUI DESC;
END
GO

CREATE OR ALTER PROCEDURE sp_sendMessage
    @MaPhong INT,
    @MaNV_Gui VARCHAR(20),
    @NoiDung NVARCHAR(MAX),
    @FileUrl NVARCHAR(MAX) = NULL,
    @FileType VARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Inserted TABLE (
        MATN INT, MAPHONG INT, MANV_GUI VARCHAR(20), 
        NOIDUNG NVARCHAR(MAX), THOIGIANGUI DATETIME, 
        FILEURL NVARCHAR(MAX), FILETYPE VARCHAR(50)
    );

    INSERT INTO TIN_NHAN (MAPHONG, MANV_GUI, NOIDUNG, FILEURL, FILETYPE)
    OUTPUT INSERTED.MATN, INSERTED.MAPHONG, INSERTED.MANV_GUI, INSERTED.NOIDUNG, INSERTED.THOIGIANGUI, INSERTED.FILEURL, INSERTED.FILETYPE
    INTO @Inserted
    VALUES (@MaPhong, @MaNV_Gui, @NoiDung, @FileUrl, @FileType);

    SELECT * FROM @Inserted;
END
GO

CREATE OR ALTER PROCEDURE sp_getRoomMembers
    @MAPHONG INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT tv.MAPHONG, tv.MANV, tv.VAITRO, tv.NGAYTHAMGIA, nv.TENNV
    FROM THANH_VIEN_PHONG_CHAT tv
    LEFT JOIN NHANVIEN nv ON tv.MANV = nv.MANV
    WHERE tv.MAPHONG = @MAPHONG;
END
GO

CREATE OR ALTER PROCEDURE sp_findDirectRoom
    @MANVA VARCHAR(20),
    @MANVB VARCHAR(20),
    @LOAIPHONG TINYINT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT p.*
    FROM PHONG_CHAT p
    INNER JOIN THANH_VIEN_PHONG_CHAT tv1 ON p.MAPHONG = tv1.MAPHONG AND tv1.MANV = @MANVA
    INNER JOIN THANH_VIEN_PHONG_CHAT tv2 ON p.MAPHONG = tv2.MAPHONG AND tv2.MANV = @MANVB
    WHERE p.LOAIPHONG = @LOAIPHONG
      AND (SELECT COUNT(*) FROM THANH_VIEN_PHONG_CHAT WHERE MAPHONG = p.MAPHONG) = 2;
END
GO

CREATE OR ALTER PROCEDURE sp_createDirectRoom
    @MANVA VARCHAR(20),
    @MANVB VARCHAR(20),
    @LOAIPHONG TINYINT,
    @MATHAMCHIEU VARCHAR(50)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @NewRoomId INT;
    
    INSERT INTO PHONG_CHAT (LOAIPHONG, MATHAMCHIEU)
    VALUES (@LOAIPHONG, @MATHAMCHIEU);
    
    SET @NewRoomId = SCOPE_IDENTITY();
    
    INSERT INTO THANH_VIEN_PHONG_CHAT (MAPHONG, MANV, VAITRO)
    VALUES 
        (@NewRoomId, @MANVA, N'Thành viên'),
        (@NewRoomId, @MANVB, N'Thành viên');
        
    SELECT * FROM PHONG_CHAT WHERE MAPHONG = @NewRoomId;
END
GO

CREATE OR ALTER PROCEDURE sp_getOrCreateReferenceRoom
    @LOAIPHONG TINYINT,
    @MATHAMCHIEU VARCHAR(50),
    @TENPHONG NVARCHAR(255) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @RoomId INT;
    
    SELECT @RoomId = MAPHONG FROM PHONG_CHAT 
    WHERE LOAIPHONG = @LOAIPHONG AND MATHAMCHIEU = @MATHAMCHIEU;
    
    IF @RoomId IS NULL
    BEGIN
        INSERT INTO PHONG_CHAT (LOAIPHONG, MATHAMCHIEU, TENPHONG)
        VALUES (@LOAIPHONG, @MATHAMCHIEU, @TENPHONG);
        
        SET @RoomId = SCOPE_IDENTITY();
    END
    
    SELECT * FROM PHONG_CHAT WHERE MAPHONG = @RoomId;
END
GO

CREATE OR ALTER PROCEDURE sp_addRoomMember
    @MAPHONG INT,
    @MANV VARCHAR(20),
    @VAITRO NVARCHAR(50) = N'Thành viên'
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM THANH_VIEN_PHONG_CHAT WHERE MAPHONG = @MAPHONG AND MANV = @MANV)
    BEGIN
        INSERT INTO THANH_VIEN_PHONG_CHAT (MAPHONG, MANV, VAITRO)
        VALUES (@MAPHONG, @MANV, @VAITRO);
    END
END
GO

CREATE OR ALTER PROCEDURE sp_removeRoomMember
    @MAPHONG INT,
    @MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM THANH_VIEN_PHONG_CHAT
    WHERE MAPHONG = @MAPHONG AND MANV = @MANV;
END
GO

CREATE OR ALTER PROCEDURE sp_getDepartmentMembers
    @MAPHG INT
AS
BEGIN
    SET NOCOUNT ON;
    -- Assuming NHANVIEN has PHG column or similar for department ID
    SELECT MANV FROM NHANVIEN WHERE PHG = @MAPHG;
END
GO

CREATE OR ALTER PROCEDURE sp_getProjectMembersSimple
    @MADA INT
AS
BEGIN
    SET NOCOUNT ON;
    -- Assuming PHANCONG table has MADA and MA_NVIEN columns
    SELECT MA_NVIEN AS MANV FROM PHANCONG WHERE MADA = @MADA;
END
GO

CREATE OR ALTER PROCEDURE sp_getProjectInfo
    @MADA INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM DEAN WHERE MADA = @MADA;
END
GO

CREATE OR ALTER PROCEDURE sp_getDepartmentInfo
    @MAPHG INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM PHONGBAN WHERE MAPHG = @MAPHG;
END
GO

CREATE OR ALTER PROCEDURE sp_createCustomGroupRoom
    @CREATORMANV VARCHAR(20),
    @TENPHONG NVARCHAR(255),
    @MATHAMCHIEU VARCHAR(50),
    @MEMBERIDS NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @NewRoomId INT;
    
    INSERT INTO PHONG_CHAT (LOAIPHONG, MATHAMCHIEU, TENPHONG)
    VALUES (4, @MATHAMCHIEU, @TENPHONG); -- LOAIPHONG = 4 (GROUP)
    
    SET @NewRoomId = SCOPE_IDENTITY();
    
    -- Insert members from comma separated string
    INSERT INTO THANH_VIEN_PHONG_CHAT (MAPHONG, MANV, VAITRO)
    SELECT DISTINCT @NewRoomId, LTRIM(RTRIM(value)), N'Thành viên'
    FROM STRING_SPLIT(@MEMBERIDS, ',');
    
    -- Ensure creator is in the room as admin
    IF NOT EXISTS (SELECT 1 FROM THANH_VIEN_PHONG_CHAT WHERE MAPHONG = @NewRoomId AND MANV = @CREATORMANV)
    BEGIN
        INSERT INTO THANH_VIEN_PHONG_CHAT (MAPHONG, MANV, VAITRO)
        VALUES (@NewRoomId, @CREATORMANV, N'Quản trị viên');
    END
    ELSE
    BEGIN
        UPDATE THANH_VIEN_PHONG_CHAT
        SET VAITRO = N'Quản trị viên'
        WHERE MAPHONG = @NewRoomId AND MANV = @CREATORMANV;
    END

    SELECT * FROM PHONG_CHAT WHERE MAPHONG = @NewRoomId;
END
GO

CREATE OR ALTER PROCEDURE sp_getRoomMemberRole
    @MAPHONG INT,
    @MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT VAITRO FROM THANH_VIEN_PHONG_CHAT
    WHERE MAPHONG = @MAPHONG AND MANV = @MANV;
END
GO