import departmentRepository from "../repositories/departmentRepository";
import chatService from "./chatService";

const departmentService = {
  getAllDepartments: async () => {
    const result = await departmentRepository.getAllDepartments();
    return {
      success: true,
      data: result,
    };
  },

  getDepartmentWithEmployees: async (maPhg) => {
    const dept = await departmentRepository.getDepartmentById(maPhg);
    if (!dept) {
      throw new Error("Phòng ban không tồn tại.");
    }
    const employees =
      await departmentRepository.getEmployeesByDepartment(maPhg);
    return {
      success: true,
      data: {
        ...dept,
        employees,
      },
    };
  },

  createDepartment: async (data) => {
    try {
      const tenPhongBan = data.tenpb || data.TEN_PB;
      // Validate tên phòng ban
      if (!tenPhongBan || tenPhongBan.trim() === "") {
        throw new Error("Tên phòng ban là bắt buộc.");
      }

      let MA_PHG = data.MA_PHG;
      let isAutoGenerated = false;

      // Nếu không gửi MA_PHG, tự động sinh ID
      if (!MA_PHG || MA_PHG <= 0) {
        try {
          const allDepts = await departmentRepository.getAllDepartments();

          // Lấy các ID hợp lệ từ danh sách phòng ban
          // ⚠️ IMPORTANT: Database returns MAPHG (uppercase), not MaPhg!
          const validIds =
            allDepts && allDepts.length > 0
              ? allDepts
                  .map((d) => {
                    // Try all possible field names: MAPHG (actual), MaPhg, MA_PHG
                    const id =
                      parseInt(d.MAPHG) ||
                      parseInt(d.MaPhg) ||
                      parseInt(d.MA_PHG) ||
                      0;
                    return isNaN(id) ? 0 : id;
                  })
                  .filter((id) => id > 0)
              : [];

          const maxId = validIds.length > 0 ? Math.max(...validIds) : 0;
          MA_PHG = maxId + 1;
          isAutoGenerated = true;

          console.log(
            `[createDepartment] Auto-generated MA_PHG: ${MA_PHG}, maxId was: ${maxId}, total depts: ${validIds.length}`,
          );
        } catch (error) {
          console.error("[createDepartment] Error getting departments:", error);
          throw new Error(
            "Không thể tạo mã phòng ban tự động: " + error.message,
          );
        }
      } else {
        // Nếu user gửi MA_PHG, kiểm tra xem đã tồn tại chưa
        try {
          const existing = await departmentRepository.getDepartmentById(MA_PHG);
          if (existing) {
            throw new Error(`Mã phòng ban ${MA_PHG} đã tồn tại.`);
          }
        } catch (error) {
          if (error.message.includes("đã tồn tại")) {
            throw error;
          }
          console.error(
            "[createDepartment] Error checking existing department:",
            error,
          );
          throw new Error("Lỗi kiểm tra mã phòng ban: " + error.message);
        }
      }

      // Tạo dữ liệu để insert
      const createData = {
        MA_PHG: MA_PHG,
        tenpb: tenPhongBan.trim(),
        matruongphg: data.matruongphg || data.MATRUONGPHG || null,
        ng_thanhlap: data.ng_thanhlap || data.NG_THANHLAP || new Date(),
      };

      console.log(
        "[createDepartment] Creating department with data:",
        createData,
      );

      await departmentRepository.createDepartment(createData);
      const room = await chatService.ensureDepartmentRoomCreated(MA_PHG, tenPhongBan);
      if (room?.MaPhong) {
        await departmentRepository.updateDepartmentChatRoom(MA_PHG, room.MaPhong);
      }

      return {
        success: true,
        message: "Tạo phòng ban thành công",
        maPhg: MA_PHG,
        isAutoGenerated,
      };
    } catch (error) {
      console.error("[createDepartment] Error:", error);
      throw new Error("Lỗi tạo phòng ban: " + error.message);
    }
  },

  updateDepartment: async (id, data) => {
    try {
      console.log(
        `[updateDepartment] Updating department ${id} with data:`,
        data,
      );

      // Step 1: Kiểm tra phòng ban tồn tại
      const existing = await departmentRepository.getDepartmentById(id);
      if (!existing) {
        throw new Error(`Phòng ban với mã ${id} không tồn tại.`);
      }

      console.log(
        "[updateDepartment] Department exists, proceeding with update",
      );

      // Step 2: Thực hiện update
      const result = await departmentRepository.updateDepartment(id, data);

      console.log(
        `[updateDepartment] Update result: success=${result.success}, changed=${result.changed}`,
      );

      // Step 3: Handle result
      if (!result.success) {
        throw new Error("Cập nhật phòng ban không thành công");
      }

      return {
        success: true,
        message: result.changed
          ? "Cập nhật phòng ban thành công"
          : "Phòng ban không có thay đổi so với dữ liệu hiện tại",
        changed: result.changed,
      };
    } catch (error) {
      console.error("[updateDepartment] Error:", error);
      throw new Error("Lỗi cập nhật phòng ban: " + error.message);
    }
  },

  deleteDepartment: async (id) => {
    try {
      await departmentRepository.deleteDepartment(id);
      return {
        success: true,
        message: "Xóa phòng ban thành công",
      };
    } catch (error) {
      throw new Error("Lỗi xóa phòng ban: " + error.message);
    }
  },

  getEmployeeDepartments: async (MA_NV, requesterMaNv, requesterRole) => {
    try {
      // Kiểm tra quyền: chỉ admin hoặc chính người đó mới xem được
      if (requesterRole !== "admin" && requesterMaNv !== MA_NV) {
        throw new Error("Bạn không có quyền xem thông tin này.");
      }

      const result = await departmentRepository.getDepartmentsByEmployee(MA_NV);
      return {
        success: true,
        data: result,
      };
    } catch (error) {
      throw new Error("Lỗi lấy danh sách phòng ban: " + error.message);
    }
  },

  getEmployeeDepartmentWithMembers: async (
    MA_NV,
    requesterMaNv,
    requesterRole,
  ) => {
    try {
      // Kiểm tra quyền
      if (requesterRole !== "admin" && requesterMaNv !== MA_NV) {
        throw new Error("Bạn không có quyền xem thông tin này.");
      }

      const result =
        await departmentRepository.getDepartmentDetailsByEmployee(MA_NV);
      return {
        success: true,
        data: result,
      };
    } catch (error) {
      throw new Error("Lỗi lấy thông tin phòng ban: " + error.message);
    }
  },
};

export default departmentService;
